############################################################
#
# Author(s):       Georg Schnabel
# Email:           g.schnabel@iaea.org
# Creation date:   2024/03/28
# Last modified:   2026/05/13
# License:         MIT
# Copyright (c) 2024-2026 International Atomic Energy Agency (IAEA)
#
############################################################

from . import cpp_boilerplate
from .code_generator_parsing import generate_all_cpp_parsefuns_code
from .code_generator_writing import generate_all_cpp_writefuns_code
from hashlib import md5


def generate_cpp_module_code(recipes, module_name, shared_registry=None):
    """Emit one ENDF flavor's pybind11 module source.

    When ``shared_registry`` is provided, the heavy per-(mf, mt) parse and
    write function bodies are routed into the registry under canonical,
    recipe-hash-derived names, and the per-flavor source emits only
    forward declarations plus the small wrappers, dispatcher, and
    PYBIND11_MODULE block. The caller is responsible for emitting the
    accumulated registry as a single ``_shared.cpp`` compiled once.
    """
    parsefuns_code, parsefuns_pybind_glue = generate_all_cpp_parsefuns_code(
        recipes, module_name, shared_registry=shared_registry
    )
    writefuns_code, writefuns_pybind_glue = generate_all_cpp_writefuns_code(
        recipes, module_name, shared_registry=shared_registry
    )

    funs_code = parsefuns_code + writefuns_code
    pybind_glue = parsefuns_pybind_glue + writefuns_pybind_glue

    module_header = cpp_boilerplate.module_header()
    pybind_glue = cpp_boilerplate.register_pybind_module(module_name, pybind_glue)
    code = module_header + funs_code + pybind_glue

    md5hash = md5(code.encode()).hexdigest()
    header = "// File generated by endf_parserpy.compiler.endf2cpp.py::generate_cpp_module_code\n"
    header += "// MD5 hash of file content below this line: "
    header += md5hash
    header += "\n"
    return header + code


def generate_shared_cpp_code(shared_registry):
    """Emit the single ``_shared.cpp`` source that holds every unique
    parse_recipe_<hash>_istream and write_recipe_<hash>_ostream body
    collected across all flavors. Each flavor's .so links against the
    object file produced from this source.
    """
    parts = []
    parts.append(cpp_boilerplate.module_header())
    parse_reg = shared_registry.get("parse", {})
    write_reg = shared_registry.get("write", {})
    parts.append(
        "// === Deduplicated parse functions (canonical names derived from recipe MD5) ===\n"
    )
    for recipe_hash, (_canonical, code) in sorted(parse_reg.items()):
        parts.append(code)
    parts.append(
        "\n// === Deduplicated write functions (canonical names derived from recipe MD5) ===\n"
    )
    for recipe_hash, (_canonical, code) in sorted(write_reg.items()):
        parts.append(code)
    body = "".join(parts)
    md5hash = md5(body.encode()).hexdigest()
    header = (
        "// File generated by endf_parserpy.compiler.endf2cpp.py::generate_shared_cpp_code\n"
        "// MD5 hash of file content below this line: " + md5hash + "\n"
    )
    return header + body
